### ISSUE TITLE
proxy settings wildcard

### ISSUE THREAD

**Issue by abdellahaski** [pjjonesnz/directadmin_cloudflare_dns#5]
Is there a posiblity to do this ? 

![image](https://user-images.githubusercontent.com/10819089/98419630-c56e2000-2085-11eb-90db-779560f62fa0.png)

or maybe disable it for CNAMEs only and keep it enabled for other dns records

**Comment by pjjonesnz** [comment]
There's definitely a possibility to do that.

My concern would be how to achieve wildcard matching like this, as 
[wildcards can be used in DNS records](https://en.wikipedia.org/wiki/Wildcard_DNS_record), so that could cause a conflict for existing configurations.

One way around this would be to add a setting to cause all record matches to use regular expressions, instead of the current basic string matching.  This would be disabled by default.

BUT, the easiest solution would be as you mentioned, to make it so that the proxy_record could either be an object or a boolean, so you could either have:

`"CNAME": { "domain.com.": false }` - to disable a single CNAME record
 
or

`"CNAME": false` - to disable all CNAME records

This would also give the ability to set 'proxy_default' to false, and then set any record type to true to only proxy that record type.

What do you think?

**Comment by abdellahaski** [comment]
That's right, I didn't think of that, it will cause conflicts.
And yeap the regex solution would really help.

For now I'll use the later solution, I didn't know that proxy_record could take a boolean 

Thank you for the help and for the amazing plugin

**Comment by abdellahaski** [comment]
I'm having trouble setting that up this config :

![image](https://user-images.githubusercontent.com/10819089/98426593-aed1c400-2099-11eb-9d1a-bec280f16e94.png)


Should proxy A and AAAA only right ? 
I don't know why it proxy CNAME also

**Comment by pjjonesnz** [comment]
Hi @abdellahaski 

Sorry for the confusion. 

No, it can't take a boolean right now, but it wouldn't be too hard to implement that.

If that would work, I'll have a look at implementing that.

**Comment by abdellahaski** [comment]
I thought that it's already implemented.
Well I did implement that on my Directadmin installation, and for now it seems that it's working.
Along with the regular expression option, the only problem is that the regex should be a PHP regex with all special character escaped so the JSON could be decoded correctly.

I only changed the [is_proxied()](https://github.com/pjjonesnz/directadmin_cloudflare_dns/blob/4122f12fa13f1b616dc9a146ac7b78e928726c3d/da_cloudflare_dns_sync/dns_write_post_cloudflare.php#L328) function.

I might do a pull request if it's really stable.

**Comment by abdellahaski** [comment]
Another thing that I just bumped into, is:
```
subdomain.domain.com.
or
subdomain
```
Directadmin treat those record as the same record, also the parts of your plugin that adds the record to Cloudflare does the same but the [is_proxied()](https://github.com/pjjonesnz/directadmin_cloudflare_dns/blob/4122f12fa13f1b616dc9a146ac7b78e928726c3d/da_cloudflare_dns_sync/dns_write_post_cloudflare.php#L328) function doesn't, it treat that as different records.

and this is the problem so let say my `default.json` has this:
```
{
    "proxy_default": true,
    "proxy_record": {
        "A": {
          "mail": false,
          "ftp": false
        },
        "CNAME": {
        },
        "AAAA": {
        }
    }
}
```
and in the DNS management of DA, instead of entering `mail ` as the record name I entered  `mail.domain.com.` (which is correct in DA, and also the plugin will send it to Cloudflare correctly) but it will send it with the Proxy ON instead of OFF.

The solution would be either removing the domain part `(.domain.com.)` from the record name before checking the `default.json`
or appending the domain name with the already existant [qualifyRecordName()](https://github.com/pjjonesnz/directadmin_cloudflare_dns/blob/4122f12fa13f1b616dc9a146ac7b78e928726c3d/da_cloudflare_dns_sync/dns_write_post_cloudflare.php#L467) function. That's what I did, and thinking of it rn the first solution is the better one I think.

For first option a new function is needed, a function that removes the `domain.com.` if it exist.
and for the second option, what I did is that I added this line to the top of [is_proxied()](https://github.com/pjjonesnz/directadmin_cloudflare_dns/blob/4122f12fa13f1b616dc9a146ac7b78e928726c3d/da_cloudflare_dns_sync/dns_write_post_cloudflare.php#L328) function :
`$record_name = qualifyRecordName($record_name);`


Update: I'm trying to implement that first solution, but I'm wondering what it should do for `domain.com.` , I couldn't think of an option. Maybe I should get some sleep, lol

**Comment by pjjonesnz** [comment]
Hi @abdellahaski 

Thanks for your input.  Yes, what you mention above was something that needed to be considered when I wrote the script, as DirectAdmin (DA) handles the record names slightly differently than Cloudflare.

My decision in the end was to make the proxy_record setting match only exactly what you use on the DirectAdmin side of things.  So, if you enter 'mail' as the record name in DA, then you need to use 'mail' in the config file.  If you enter 'mail.domain.com.' in DA, then you need to use 'mail.domain.com.' in the config file.

That would be a tricky one to use the qualifyRecordName in because of what you mention above.

I have gone ahead and changed the is_proxied function to allow boolean values.  I've tested it on my production server and it is working correctly. Can you please have a look and see if it works for you?

Thanks again for your input - very helpful.

**Comment by abdellahaski** [comment]
Hi again,

Yes that an easy solution and a logical one, you just need to make sure that you enter the same thing on the config as well as the dns management.

I agree qualifyRecordName will tricky .

And yes the edits you made are exactly what I did so yeah it works.

Thank you also for your help
